#!/usr/bin/env python3
"""PUBLIC v0.21.30: strict dynamic-provider source of truth and fallback routing."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "app/src/main/java/com/riyan/aikeyboard"


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if new in text:
        return text
    if old not in text:
        raise RuntimeError(f"PUBLIC provider patch marker not found: {label}")
    return text.replace(old, new, 1)


# ---------------------------------------------------------------------------
# Settings panel generated by PUBLIC parity patch.
# Use PUBLIC store only, verify provider credentials before save, make fallback
# immediate, and never mirror a dynamic provider back into legacy xKiro prefs.
# ---------------------------------------------------------------------------
overlay_path = SRC / "KeyboardSettingsOverlay.kt"
overlay = overlay_path.read_text(encoding="utf-8")
MARKER = "// PUBLIC provider source-of-truth v030"
if MARKER not in overlay:
    if "privateProviderLoadedId" not in overlay:
        raise RuntimeError("PUBLIC parity provider UI must run before provider runtime patch")

    overlay = overlay.replace("PrivateProviderStore", "PublicProviderStore")
    overlay = overlay.replace("PrivateProviderProfile", "PublicProviderProfile")
    overlay = replace_once(
        overlay,
        "    private var privateProviderBusy = false\n",
        "    private var privateProviderBusy = false\n    // PUBLIC provider source-of-truth v030\n",
        "overlay marker",
    )

    old_save = '''        config.addView(actionButton(if (privateProviderBusy) "Mengambil model…" else "Simpan") {
            if (privateProviderBusy) return@actionButton
            runCatching {
                PublicProviderStore.save(
                    prefs = prefs,
                    baseUrl = draft.xKiroBaseUrl,
                    apiKey = draft.xKiroKey,
                    model = draft.xKiroModel,
                    models = privateProviderModels
                )
            }.onSuccess { profile ->
                loadPrivateProvider(profile, applyNow = true)
                privateProviderStatus = "Provider tersimpan. Mengambil daftar model…"
                refreshPrivateProviderModels(openMenu = true)
            }.onFailure { error ->
                privateProviderStatus = error.message ?: "Provider tidak bisa disimpan."
                renderBody()
            }
        }, LinearLayout.LayoutParams(-1, dp(42)).apply { topMargin = dp(8) })'''
    new_save = '''        config.addView(actionButton(if (privateProviderBusy) "Memverifikasi…" else "Simpan") {
            if (privateProviderBusy) return@actionButton
            val baseUrl = draft.xKiroBaseUrl.trim()
            val apiKey = draft.xKiroKey.trim()
            if (baseUrl.isBlank()) {
                privateProviderStatus = "Isi Base URL terlebih dahulu."
                renderBody()
                return@actionButton
            }
            privateProviderBusy = true
            privateProviderStatus = "Memverifikasi Base URL, API Key, dan daftar model…"
            renderBody()
            Thread {
                val result = PublicProviderStore.fetchModels(baseUrl, apiKey)
                post {
                    privateProviderBusy = false
                    result.onSuccess { models ->
                        privateProviderModels = models
                        val selectedModel = draft.xKiroModel.takeIf { it in models }
                            ?: models.firstOrNull().orEmpty()
                        draft.xKiroModel = selectedModel
                        val profile = PublicProviderStore.save(
                            prefs = prefs,
                            baseUrl = baseUrl,
                            apiKey = apiKey,
                            model = selectedModel,
                            models = models
                        )
                        loadPrivateProvider(profile, applyNow = true)
                        privateProviderStatus = "${profile.name} terhubung. ${models.size} model ditemukan."
                        privateProviderMenu = "model"
                    }.onFailure { error ->
                        privateProviderStatus = "Provider tidak disimpan: ${error.message ?: "Base URL/API Key tidak dapat diverifikasi."}"
                    }
                    renderBody()
                }
            }.start()
        }, LinearLayout.LayoutParams(-1, dp(42)).apply { topMargin = dp(8) })'''
    overlay = replace_once(overlay, old_save, new_save, "verified provider save")

    old_fallback = '''        body.addView(toggleCard(
            "Aktifkan Fallback Penyedia",
            "Otomatis beralih ke provider lain bila provider/model utama gagal.",
            draft.fallbackEnabled
        ) { draft.fallbackEnabled = it }, LinearLayout.LayoutParams(-1, -2).apply { topMargin = dp(10) })'''
    new_fallback = '''        body.addView(toggleCard(
            "Aktifkan Fallback Penyedia",
            "Otomatis beralih hanya ke provider lain yang masih tersimpan bila provider/model utama gagal.",
            draft.fallbackEnabled
        ) { enabled ->
            draft.fallbackEnabled = enabled
            prefs.edit().putBoolean("fallback_enabled", enabled).commit()
            onApply()
        }, LinearLayout.LayoutParams(-1, -2).apply { topMargin = dp(10) })'''
    overlay = replace_once(overlay, old_fallback, new_fallback, "immediate fallback toggle")

    old_load_apply = '''        if (applyNow) {
            prefs.edit()
                .putString("provider", AiProvider.XKIRO.id)
                .putString("xkiro_api_key", profile.apiKey)
                .putString("xkiro_base_url", profile.baseUrl)
                .putString("xkiro_model", profile.model)
                .apply()
            onApply()
        }'''
    new_load_apply = '''        if (applyNow) {
            PublicProviderStore.purgeLegacyProviderState(prefs)
            onApply()
        }'''
    overlay = replace_once(overlay, old_load_apply, new_load_apply, "remove legacy xKiro mirror")

    old_empty_delete = '''                        } else {
                            privateProviderLoadedId = null
                            privateProviderModels = emptyList()
                            draft.provider = AiProvider.XKIRO
                            draft.xKiroBaseUrl = ""
                            draft.xKiroKey = ""
                            draft.xKiroModel = ""
                            prefs.edit()
                                .putString("provider", AiProvider.XKIRO.id)
                                .putString("xkiro_api_key", "")
                                .putString("xkiro_base_url", "")
                                .putString("xkiro_model", "")
                                .apply()
                            onApply()
                            privateProviderStatus = "${profile.name} dihapus. Belum ada provider aktif."
                        }'''
    new_empty_delete = '''                        } else {
                            privateProviderLoadedId = null
                            privateProviderModels = emptyList()
                            draft.xKiroBaseUrl = ""
                            draft.xKiroKey = ""
                            draft.xKiroModel = ""
                            PublicProviderStore.purgeLegacyProviderState(prefs)
                            onApply()
                            privateProviderStatus = "${profile.name} dihapus sampai bersih. Belum ada provider aktif."
                        }'''
    overlay = replace_once(overlay, old_empty_delete, new_empty_delete, "root-clean last provider deletion")

    save_start = overlay.index("    private fun saveDraft() {")
    save_end = overlay.index("\n    private fun resetDraft()", save_start)
    save_block = overlay[save_start:save_end]
    save_block_new = save_block.replace(
        "            .apply()\n        onApply()",
        "            .apply()\n        PublicProviderStore.purgeLegacyProviderState(prefs)\n        onApply()",
        1,
    )
    if save_block_new == save_block:
        raise RuntimeError("PUBLIC provider patch marker not found: saveDraft purge")
    overlay = overlay[:save_start] + save_block_new + overlay[save_end:]
    overlay_path.write_text(overlay, encoding="utf-8")


# ---------------------------------------------------------------------------
# AiClient: one exact OpenAI-compatible provider for vision. PublicAiPolicy must
# already be installed by the existing PUBLIC AI patch and is intentionally kept.
# ---------------------------------------------------------------------------
ai_path = SRC / "AiClient.kt"
ai = ai_path.read_text(encoding="utf-8")
AI_MARKER = "// PUBLIC exact compatible vision v030"
if AI_MARKER not in ai:
    if "PublicAiPolicy.CHAT" not in ai or "PublicAiPolicy.VISION" not in ai:
        raise RuntimeError("PUBLIC AI policy missing; refusing to replace provider routing")
    insert_before = "    private fun execute(\n"
    if insert_before not in ai:
        raise RuntimeError("PUBLIC provider patch marker not found: AiClient execute")
    helper = '''    // PUBLIC exact compatible vision v030
    internal fun compatiblePublicVision(
        profile: PublicProviderProfile,
        jpegBase64: String,
        localTextHint: String = ""
    ): Result<String> = runCatching {
        require(jpegBase64.isNotBlank()) { "Gambar kosong." }
        val raw = requestCompatibleVision(
            apiKey = profile.apiKey,
            baseUrl = profile.baseUrl,
            model = profile.model,
            providerLabel = profile.name,
            jpegBase64 = jpegBase64,
            localTextHint = localTextHint
        )
        normalizeVisionResult(raw)
            ?: throw IllegalStateException("Model ${profile.name} tidak membuktikan bahwa gambar benar-benar dibaca.")
    }

'''
    ai = ai.replace(insert_before, helper + insert_before, 1)
    ai_path.write_text(ai, encoding="utf-8")


# ---------------------------------------------------------------------------
# Keyboard runtime: all PUBLIC AI actions use only the selected saved profile.
# Fallback, when enabled, may use only other profiles still in PublicProviderStore.
# The PUBLIC mic patch is a later Gradle preBuild generator; it calls the voice
# helper installed here after this shell-time patch has already completed.
# ---------------------------------------------------------------------------
service_path = SRC / "RiyanKeyboardService.kt"
service = service_path.read_text(encoding="utf-8")
SERVICE_MARKER = "// PUBLIC strict dynamic provider runtime v030"
if SERVICE_MARKER not in service:
    service = service.replace("PrivateProviderStore", "PublicProviderStore")

    ai_settings_marker = "    private fun aiSettings() = getSharedPreferences(PREFS, MODE_PRIVATE).let { prefs ->\n"
    if ai_settings_marker not in service:
        raise RuntimeError("PUBLIC provider patch marker not found: aiSettings")
    helpers = '''    // PUBLIC strict dynamic provider runtime v030
    private fun <T> runPublicProviderRequest(
        request: (PublicProviderProfile) -> Result<T>
    ): Result<PublicProviderExecution<T>> {
        val prefs = getSharedPreferences(PREFS, MODE_PRIVATE)
        val profiles = PublicProviderStore.load(prefs)
        val selected = PublicProviderStore.selected(prefs, profiles)
        val fallbackEnabled = prefs.getBoolean("fallback_enabled", false)
        return PublicProviderRuntime.execute(
            profiles = profiles,
            selectedId = selected?.id,
            fallbackEnabled = fallbackEnabled,
            request = request
        )
    }

    private fun publicSettingsFor(profile: PublicProviderProfile): AiSettings =
        aiSettings().copy(
            primaryProvider = AiProvider.XKIRO,
            xKiroApiKey = profile.apiKey,
            xKiroBaseUrl = profile.baseUrl,
            xKiroModel = profile.model,
            fallbackEnabled = false
        )

    private fun runPublicTransform(action: String, text: String): Result<PublicProviderAiResponse> =
        runPublicProviderRequest { profile ->
            AiClient.transform(publicSettingsFor(profile), action, text).map { it.text }
        }.map { PublicProviderAiResponse(it.value, it.profile) }

    private fun runPublicChat(prompt: String, context: String, history: String): Result<PublicProviderAiResponse> =
        runPublicProviderRequest { profile ->
            AiClient.chat(publicSettingsFor(profile), prompt, context, history).map { it.text }
        }.map { PublicProviderAiResponse(it.value, it.profile) }

    private fun runPublicVoiceCorrection(transcript: String): Result<PublicProviderAiResponse> =
        runPublicProviderRequest { profile ->
            AiClient.correctVoiceSearch(publicSettingsFor(profile), transcript).map { it.text }
        }.map { PublicProviderAiResponse(it.value, it.profile) }

    private fun runPublicVision(jpegBase64: String, localTextHint: String): Result<AiResponse> =
        runPublicProviderRequest { profile ->
            AiClient.compatiblePublicVision(profile, jpegBase64, localTextHint)
        }.map { AiResponse(it.value, AiProvider.XKIRO) }

'''
    service = service.replace(ai_settings_marker, helpers + ai_settings_marker, 1)

    replacements = [
        ("AiClient.correctVoiceSearch(settings, cleanTranscript).getOrNull()?.text", "runPublicVoiceCorrection(cleanTranscript).getOrNull()?.text"),
        ("AiClient.visionProduct(aiSettings(), encoded, localHint)", "runPublicVision(encoded, localHint)"),
        ("AiClient.visionProduct(aiSettings(), encoded, \"\")", "runPublicVision(encoded, \"\")"),
        ("AiClient.transform(settings, action, input)", "runPublicTransform(action, input)"),
        ("AiClient.transform(aiSettings(), action, input)", "runPublicTransform(action, input)"),
        ("AiClient.chat(aiSettings(), prompt, \"\", history)", "runPublicChat(prompt, \"\", history)"),
        ("AiClient.chat(aiSettings(), prompt, appContext, history)", "runPublicChat(prompt, appContext, history)"),
    ]
    for old, new in replacements:
        if old in service:
            service = service.replace(old, new)

    service = service.replace(
        'aiStatus.text = "Model: ${activeModelName()} · ketuk jawaban atau Pakai"',
        'aiStatus.text = "Model: ${response.profile.model} · ${response.profile.name} · ketuk jawaban atau Pakai"'
    )

    required = [
        "private fun runPublicVoiceCorrection",
        "runPublicVision(encoded, localHint)",
        "runPublicTransform(action, input)",
        "runPublicChat(prompt, \"\", history)",
        "PublicProviderStore.selected",
    ]
    missing = [item for item in required if item not in service]
    if missing:
        raise RuntimeError("PUBLIC provider runtime redirects missing: " + ", ".join(missing))

    service_path.write_text(service, encoding="utf-8")

print("Applied PUBLIC v0.21.30 strict dynamic provider runtime")
