from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SERVICE = ROOT / "app/src/main/java/com/riyan/aikeyboard/RiyanKeyboardService.kt"
HORDE = ROOT / "app/src/main/java/com/riyan/aikeyboard/AiHordeAlchemyVision.kt"
SMART = ROOT / "app/smart-vision.gradle.kts"

service = SERVICE.read_text(encoding="utf-8")

old_gallery = '''            val visualUrl: String? = null // Brave Search remains the embedded search surface.
            val result = if (encoded.isNullOrBlank()) {
                Result.failure<AiResponse>(IllegalStateException("Gambar galeri gagal disiapkan."))
            } else {
                AiClient.visionProduct(aiSettings(), encoded, "")
            }'''
new_gallery = '''            val galleryLocalHint = runCatching {
                VisionSearchEvidence.recognizeText(scannerTextRecognizer, prepared)
            }.getOrDefault("")
            val visualUrl: String? = null // embedded search surface
            val result = if (encoded.isNullOrBlank()) {
                Result.failure<AiResponse>(IllegalStateException("Gambar galeri gagal disiapkan."))
            } else {
                AiClient.visionProduct(aiSettings(), encoded, galleryLocalHint)
            }'''

if "VisionSearchEvidence.recognizeText(scannerTextRecognizer, prepared)" not in service:
    if old_gallery not in service:
        raise RuntimeError("Gallery OCR compatibility marker not found")
    service = service.replace(old_gallery, new_gallery, 1)

SERVICE.write_text(service, encoding="utf-8")

# Fix the three language branches generated by the main patch. In Kotlin an if-expression
# uses `else value` rather than the `else -> value` syntax used by a when-entry.
horde = HORDE.read_text(encoding="utf-8")
pattern = re.compile(r'("person" -> if \(ageUnclear\)\n\s+"[^"]+")\n(\s+)else -> ("[^"]+")')
horde, fixes = pattern.subn(lambda m: f"{m.group(1)}\n{m.group(2)}else {m.group(3)}", horde)
if fixes not in (0, 3):
    raise RuntimeError(f"Unexpected adult-person language branch fix count: {fixes}")
HORDE.write_text(horde, encoding="utf-8")

# The legacy Gradle smart-vision task enforced English-only, short human prompts and
# rewrote multilingual output back to English. The new persistent Python patch now owns
# Vision behavior, so keep only the task/dependency name for build compatibility.
SMART.write_text('''// Vision/search behavior is applied by tools/apply_vision_search_google_patch.py.
// This compatibility task intentionally performs no source rewriting so multilingual,
// long prompts and the Google-default search behavior are not overwritten at preBuild.
val patchSmartProductVision = tasks.register("patchSmartProductVision") {
    doLast {
        println("Multilingual natural Vision/search patch already applied; legacy smart-vision rewrite skipped")
    }
}

patchSmartProductVision.configure {
    mustRunAfter("patchDynamicImeAction")
    mustRunAfter("patchBluesMindsProvider")
    mustRunAfter("patchSettingsInputAndGallery")
    mustRunAfter("patchReferenceBrandingAndKeyCentering")
    mustRunAfter("patchVisibleVersionLabel")
}

tasks.named("preBuild").configure {
    dependsOn(patchSmartProductVision)
}
''', encoding="utf-8")

print(f"Applied gallery OCR compatibility, fixed {fixes} multilingual person branches, and disabled obsolete English-only smart Vision rewrite")
