#!/usr/bin/env python3
"""Apply only PRIVATE input behavior after the existing build patches."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
p = ROOT / "app/src/main/java/com/riyan/aikeyboard/RiyanKeyboardService.kt"
s = p.read_text()
replacements = [('        var downX = 0f\n'
  '        var downY = 0f\n'
  '        var longTriggered = false\n'
  '        var actionTriggered = false\n'
  '        var longRunnable: Runnable? = null\n'
  '        frame.setOnTouchListener { view, event ->\n'
  '            when (event.actionMasked) {\n'
  '                MotionEvent.ACTION_DOWN -> {\n'
  '                    downX = event.x\n'
  '                    downY = event.y\n'
  '                    longTriggered = false\n'
  '                    actionTriggered = false\n'
  '                    keyFace.background = referenceBubbleKeyBackground(pressed = true, baseColor = '
  'normalColor)\n'
  '                    val shiftKey = spec.label == "⇧" || spec.label == "⇪"\n'
  '                    if (instantKeyResponse) {\n'
  '                        // Haptic stays on ACTION_DOWN, before any action/render work.\n'
  '                        keyFeedback(view, longPress = false)\n'
  '                    }\n'
  '                    if (keyPreviewEnabled) showKeyPreview(view, spec)\n'
  '                    if (instantKeyResponse && !shiftKey) {\n'
  '                        spec.action()\n'
  '                        actionTriggered = true\n'
  '                    }\n'
  '                    spec.longAction?.let { longAction ->\n'
  '                        longRunnable = Runnable {\n'
  '                            longTriggered = true\n'
  '                            if (actionTriggered && spec.alternate != null) '
  'deleteInstantCommittedCharacter()\n'
  '                            spec.alternate?.let(::updateKeyPreview)\n'
  '                            longAction()\n'
  '                            keyFeedback(view, longPress = true)\n'
  '                        }.also { handler.postDelayed(it, longPressDurationMs) }\n'
  '                    }\n'
  '                    true\n'
  '                }\n'
  '                MotionEvent.ACTION_MOVE -> {\n'
  '                    if (hypot(event.x - downX, event.y - downY) > touchTolerancePx) {\n'
  '                        longRunnable?.let(handler::removeCallbacks)\n'
  '                    }\n'
  '                    true\n'
  '                }\n'
  '                MotionEvent.ACTION_UP -> {\n'
  '                    longRunnable?.let(handler::removeCallbacks)\n'
  '                    dismissKeyPreview()\n'
  '                    keyFace.background = referenceBubbleKeyBackground(pressed = false, baseColor = '
  'normalColor)\n'
  '                    val moved = hypot(event.x - downX, event.y - downY)\n'
  '                    if (!longTriggered && !actionTriggered && moved <= touchTolerancePx) {\n'
  '                        val shiftKey = spec.label == "⇧" || spec.label == "⇪"\n'
  '                        // Shift already vibrated on ACTION_DOWN in instant mode. Other release-mode\n'
  '                        // keys vibrate here, still before their action.\n'
  '                        if (!(instantKeyResponse && shiftKey)) {\n'
  '                            keyFeedback(view, longPress = false)\n'
  '                        }\n'
  '                        spec.action()\n'
  '                        actionTriggered = true\n'
  '                    }\n'
  '                    true\n'
  '                }\n'
  '                MotionEvent.ACTION_CANCEL -> {\n'
  '                    longRunnable?.let(handler::removeCallbacks)\n'
  '                    dismissKeyPreview()\n'
  '                    keyFace.background = referenceBubbleKeyBackground(pressed = false, baseColor = '
  'normalColor)\n'
  '                    true\n'
  '                }\n'
  '                else -> false\n'
  '            }\n'
  '        }\n',
  '        val touch = PrivateKeyTouchListener(\n'
  '            handler = handler,\n'
  '            holdMs = longPressDurationMs,\n'
  '            tolerance = touchTolerancePx,\n'
  '            feedback = { longPress -> keyFeedback(frame, longPress) },\n'
  '            pressed = { pressed ->\n'
  '                keyFace.background = referenceBubbleKeyBackground(pressed = pressed, baseColor = '
  'normalColor)\n'
  '            },\n'
  '            preview = { if (keyPreviewEnabled) showKeyPreview(frame, spec) },\n'
  '            hidePreview = { dismissKeyPreview() },\n'
  '            alternatePreview = { spec.alternate?.let(::updateKeyPreview) },\n'
  '            tap = spec.action,\n'
  '            hold = spec.longAction\n'
  '        )\n'
  '        frame.setOnTouchListener(touch)\n'
  '        frame.addOnAttachStateChangeListener(touch)\n'),
 ('    private fun addRow(specs: List<KeySpec>) {\n'
  '        val isFirstKeyboardRow = keyboardPanel.childCount == 0\n'
  '        val row = LinearLayout(this).apply {\n'
  '            orientation = LinearLayout.HORIZONTAL\n'
  '            gravity = Gravity.CENTER\n'
  '        }\n'
  '        specs.forEach { spec ->\n'
  '            if (spec.label.isEmpty()) {\n'
  '                row.addView(View(this), LinearLayout.LayoutParams(0, -1, spec.weight))\n'
  '            } else {\n'
  '                row.addView(keyView(spec), LinearLayout.LayoutParams(0, -1, spec.weight).apply {\n'
  '                    setMargins(dpFloat(0.5f).toInt().coerceAtLeast(1), '
  'dpFloat(0.5f).toInt().coerceAtLeast(1), dpFloat(0.5f).toInt().coerceAtLeast(1), '
  'dpFloat(0.5f).toInt().coerceAtLeast(1))\n'
  '                })\n'
  '            }\n'
  '        }\n'
  '        keyboardPanel.addView(row, LinearLayout.LayoutParams(-1, 0, 1f))\n'
  '    }\n'
  '\n',
  '    private fun addRow(specs: List<KeySpec>) {\n'
  '        val isFirstKeyboardRow = keyboardPanel.childCount == 0\n'
  '        val row = PrivateKeyRow(this).apply {\n'
  '            orientation = LinearLayout.HORIZONTAL\n'
  '            gravity = Gravity.CENTER\n'
  '        }\n'
  '        specs.forEach { spec ->\n'
  '            if (spec.label.isEmpty()) {\n'
  '                row.addView(View(this), LinearLayout.LayoutParams(0, -1, spec.weight))\n'
  '            } else {\n'
  '                row.addView(keyView(spec), LinearLayout.LayoutParams(0, -1, spec.weight).apply {\n'
  '                    setMargins(dpFloat(0.5f).toInt().coerceAtLeast(1), '
  'dpFloat(0.5f).toInt().coerceAtLeast(1), dpFloat(0.5f).toInt().coerceAtLeast(1), '
  'dpFloat(0.5f).toInt().coerceAtLeast(1))\n'
  '                })\n'
  '            }\n'
  '        }\n'
  '        keyboardPanel.addView(row, LinearLayout.LayoutParams(-1, 0, 1f))\n'
  '    }\n'
  '\n'),
 ('        if (before.isNotBlank() && !before.last().isWhitespace() && currentFragment.length < 2) {',
  '        val emojiCandidates = PrivateEmojiSuggestions.suggest(before)\n'
  '        if (emojiCandidates.isEmpty() && before.isNotBlank() && !before.last().isWhitespace() && '
  'currentFragment.length < 2) {'),
 ('        if (candidates.isEmpty()) {', '        if (candidates.isEmpty() && emojiCandidates.isEmpty()) {'),
 ('        candidates.forEach { candidate ->',
  '        emojiCandidates.forEach { emoji ->\n'
  '            suggestionBar.addView(TextView(this).apply {\n'
  '                text = emoji\n'
  '                textSize = 17f\n'
  '                gravity = Gravity.CENTER\n'
  '                contentDescription = "Emoji: $emoji"\n'
  '                setOnClickListener {\n'
  '                    keyFeedback(this, longPress = false)\n'
  '                    commitToTarget(emoji)\n'
  '                    rememberEmoji(emoji)\n'
  '                    refreshSuggestionsSoon()\n'
  '                }\n'
  '            }, LinearLayout.LayoutParams(dp(28), -1))\n'
  '        }\n'
  '        candidates.take(if (emojiCandidates.isEmpty()) 2 else 1).forEach { candidate ->'),
 ('handler.postDelayed(suggestionRefreshRunnable, if (fastTypingMode) 700L else 220L)',
  'handler.postDelayed(suggestionRefreshRunnable, 80L)'),
 ('keyPreviewEnabled = prefs.getBoolean("key_preview_enabled", false)',
  'keyPreviewEnabled = prefs.getBoolean("key_preview_enabled", true)')]
for old, new in replacements:
    if new in s:
        continue
    if old not in s:
        raise RuntimeError("PRIVATE touch/emoji marker missing: " + old[:100])
    s = s.replace(old, new, 1)
p.write_text(s)
p = ROOT / "app/src/main/java/com/riyan/aikeyboard/KeyboardSettingsOverlay.kt"
s = p.read_text().replace('keyPreview = prefs.getBoolean("key_preview_enabled", false)', 'keyPreview = prefs.getBoolean("key_preview_enabled", true)')
p.write_text(s)
print("Applied PRIVATE gap hit targets, feedback-first exclusive long press, and offline emoji suggestions")
